[package]
name = "jvrcruz/trustsdk"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "TrustSDK, a Roblox library for secure network communication"
include = ["lib"]

[dependencies]
cryptography = "daily3014/cryptography@3.1.1"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
RoactCompat = "jsdotlua/roact-compat@17.2.1"